// +build !ignore_autogenerated

/*
@asiainfo.com
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1

import (
	prd "github.com/asiainfoldp/apiserver-servicebroker/pkg/apis/prd"
	core_v1 "k8s.io/api/core/v1"
	meta "k8s.io/apimachinery/pkg/apis/meta"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1_BackingService_To_prd_BackingService,
		Convert_prd_BackingService_To_v1_BackingService,
		Convert_v1_BackingServiceInstance_To_prd_BackingServiceInstance,
		Convert_prd_BackingServiceInstance_To_v1_BackingServiceInstance,
		Convert_v1_BackingServiceInstanceList_To_prd_BackingServiceInstanceList,
		Convert_prd_BackingServiceInstanceList_To_v1_BackingServiceInstanceList,
		Convert_v1_BackingServiceInstanceSpec_To_prd_BackingServiceInstanceSpec,
		Convert_prd_BackingServiceInstanceSpec_To_v1_BackingServiceInstanceSpec,
		Convert_v1_BackingServiceInstanceStatus_To_prd_BackingServiceInstanceStatus,
		Convert_prd_BackingServiceInstanceStatus_To_v1_BackingServiceInstanceStatus,
		Convert_v1_BackingServiceInstanceStatusStrategy_To_prd_BackingServiceInstanceStatusStrategy,
		Convert_prd_BackingServiceInstanceStatusStrategy_To_v1_BackingServiceInstanceStatusStrategy,
		Convert_v1_BackingServiceInstanceStrategy_To_prd_BackingServiceInstanceStrategy,
		Convert_prd_BackingServiceInstanceStrategy_To_v1_BackingServiceInstanceStrategy,
		Convert_v1_BackingServiceList_To_prd_BackingServiceList,
		Convert_prd_BackingServiceList_To_v1_BackingServiceList,
		Convert_v1_BackingServiceSpec_To_prd_BackingServiceSpec,
		Convert_prd_BackingServiceSpec_To_v1_BackingServiceSpec,
		Convert_v1_BackingServiceStatus_To_prd_BackingServiceStatus,
		Convert_prd_BackingServiceStatus_To_v1_BackingServiceStatus,
		Convert_v1_BackingServiceStatusStrategy_To_prd_BackingServiceStatusStrategy,
		Convert_prd_BackingServiceStatusStrategy_To_v1_BackingServiceStatusStrategy,
		Convert_v1_BackingServiceStrategy_To_prd_BackingServiceStrategy,
		Convert_prd_BackingServiceStrategy_To_v1_BackingServiceStrategy,
		Convert_v1_Binding_To_prd_Binding,
		Convert_prd_Binding_To_v1_Binding,
		Convert_v1_BindingList_To_prd_BindingList,
		Convert_prd_BindingList_To_v1_BindingList,
		Convert_v1_CustomizeSpec_To_prd_CustomizeSpec,
		Convert_prd_CustomizeSpec_To_v1_CustomizeSpec,
		Convert_v1_InstanceBinding_To_prd_InstanceBinding,
		Convert_prd_InstanceBinding_To_v1_InstanceBinding,
		Convert_v1_InstanceProvisioning_To_prd_InstanceProvisioning,
		Convert_prd_InstanceProvisioning_To_v1_InstanceProvisioning,
		Convert_v1_LastOperation_To_prd_LastOperation,
		Convert_prd_LastOperation_To_v1_LastOperation,
		Convert_v1_ServiceBroker_To_prd_ServiceBroker,
		Convert_prd_ServiceBroker_To_v1_ServiceBroker,
		Convert_v1_ServiceBrokerList_To_prd_ServiceBrokerList,
		Convert_prd_ServiceBrokerList_To_v1_ServiceBrokerList,
		Convert_v1_ServiceBrokerSpec_To_prd_ServiceBrokerSpec,
		Convert_prd_ServiceBrokerSpec_To_v1_ServiceBrokerSpec,
		Convert_v1_ServiceBrokerStatus_To_prd_ServiceBrokerStatus,
		Convert_prd_ServiceBrokerStatus_To_v1_ServiceBrokerStatus,
		Convert_v1_ServiceBrokerStatusStrategy_To_prd_ServiceBrokerStatusStrategy,
		Convert_prd_ServiceBrokerStatusStrategy_To_v1_ServiceBrokerStatusStrategy,
		Convert_v1_ServiceBrokerStrategy_To_prd_ServiceBrokerStrategy,
		Convert_prd_ServiceBrokerStrategy_To_v1_ServiceBrokerStrategy,
		Convert_v1_ServicePlan_To_prd_ServicePlan,
		Convert_prd_ServicePlan_To_v1_ServicePlan,
		Convert_v1_ServicePlanCost_To_prd_ServicePlanCost,
		Convert_prd_ServicePlanCost_To_v1_ServicePlanCost,
		Convert_v1_ServicePlanMetadata_To_prd_ServicePlanMetadata,
		Convert_prd_ServicePlanMetadata_To_v1_ServicePlanMetadata,
		Convert_v1_UserProvidedService_To_prd_UserProvidedService,
		Convert_prd_UserProvidedService_To_v1_UserProvidedService,
	)
}

func autoConvert_v1_BackingService_To_prd_BackingService(in *BackingService, out *prd.BackingService, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_BackingServiceSpec_To_prd_BackingServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_BackingServiceStatus_To_prd_BackingServiceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_BackingService_To_prd_BackingService is an autogenerated conversion function.
func Convert_v1_BackingService_To_prd_BackingService(in *BackingService, out *prd.BackingService, s conversion.Scope) error {
	return autoConvert_v1_BackingService_To_prd_BackingService(in, out, s)
}

func autoConvert_prd_BackingService_To_v1_BackingService(in *prd.BackingService, out *BackingService, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_prd_BackingServiceSpec_To_v1_BackingServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_prd_BackingServiceStatus_To_v1_BackingServiceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_prd_BackingService_To_v1_BackingService is an autogenerated conversion function.
func Convert_prd_BackingService_To_v1_BackingService(in *prd.BackingService, out *BackingService, s conversion.Scope) error {
	return autoConvert_prd_BackingService_To_v1_BackingService(in, out, s)
}

func autoConvert_v1_BackingServiceInstance_To_prd_BackingServiceInstance(in *BackingServiceInstance, out *prd.BackingServiceInstance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_BackingServiceInstanceSpec_To_prd_BackingServiceInstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_BackingServiceInstanceStatus_To_prd_BackingServiceInstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_BackingServiceInstance_To_prd_BackingServiceInstance is an autogenerated conversion function.
func Convert_v1_BackingServiceInstance_To_prd_BackingServiceInstance(in *BackingServiceInstance, out *prd.BackingServiceInstance, s conversion.Scope) error {
	return autoConvert_v1_BackingServiceInstance_To_prd_BackingServiceInstance(in, out, s)
}

func autoConvert_prd_BackingServiceInstance_To_v1_BackingServiceInstance(in *prd.BackingServiceInstance, out *BackingServiceInstance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_prd_BackingServiceInstanceSpec_To_v1_BackingServiceInstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_prd_BackingServiceInstanceStatus_To_v1_BackingServiceInstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_prd_BackingServiceInstance_To_v1_BackingServiceInstance is an autogenerated conversion function.
func Convert_prd_BackingServiceInstance_To_v1_BackingServiceInstance(in *prd.BackingServiceInstance, out *BackingServiceInstance, s conversion.Scope) error {
	return autoConvert_prd_BackingServiceInstance_To_v1_BackingServiceInstance(in, out, s)
}

func autoConvert_v1_BackingServiceInstanceList_To_prd_BackingServiceInstanceList(in *BackingServiceInstanceList, out *prd.BackingServiceInstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]prd.BackingServiceInstance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_BackingServiceInstanceList_To_prd_BackingServiceInstanceList is an autogenerated conversion function.
func Convert_v1_BackingServiceInstanceList_To_prd_BackingServiceInstanceList(in *BackingServiceInstanceList, out *prd.BackingServiceInstanceList, s conversion.Scope) error {
	return autoConvert_v1_BackingServiceInstanceList_To_prd_BackingServiceInstanceList(in, out, s)
}

func autoConvert_prd_BackingServiceInstanceList_To_v1_BackingServiceInstanceList(in *prd.BackingServiceInstanceList, out *BackingServiceInstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]BackingServiceInstance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_prd_BackingServiceInstanceList_To_v1_BackingServiceInstanceList is an autogenerated conversion function.
func Convert_prd_BackingServiceInstanceList_To_v1_BackingServiceInstanceList(in *prd.BackingServiceInstanceList, out *BackingServiceInstanceList, s conversion.Scope) error {
	return autoConvert_prd_BackingServiceInstanceList_To_v1_BackingServiceInstanceList(in, out, s)
}

func autoConvert_v1_BackingServiceInstanceSpec_To_prd_BackingServiceInstanceSpec(in *BackingServiceInstanceSpec, out *prd.BackingServiceInstanceSpec, s conversion.Scope) error {
	if err := Convert_v1_InstanceProvisioning_To_prd_InstanceProvisioning(&in.InstanceProvisioning, &out.InstanceProvisioning, s); err != nil {
		return err
	}
	if err := Convert_v1_UserProvidedService_To_prd_UserProvidedService(&in.UserProvidedService, &out.UserProvidedService, s); err != nil {
		return err
	}
	out.Binding = *(*[]prd.InstanceBinding)(unsafe.Pointer(&in.Binding))
	out.Bound = in.Bound
	out.InstanceID = in.InstanceID
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	return nil
}

// Convert_v1_BackingServiceInstanceSpec_To_prd_BackingServiceInstanceSpec is an autogenerated conversion function.
func Convert_v1_BackingServiceInstanceSpec_To_prd_BackingServiceInstanceSpec(in *BackingServiceInstanceSpec, out *prd.BackingServiceInstanceSpec, s conversion.Scope) error {
	return autoConvert_v1_BackingServiceInstanceSpec_To_prd_BackingServiceInstanceSpec(in, out, s)
}

func autoConvert_prd_BackingServiceInstanceSpec_To_v1_BackingServiceInstanceSpec(in *prd.BackingServiceInstanceSpec, out *BackingServiceInstanceSpec, s conversion.Scope) error {
	if err := Convert_prd_InstanceProvisioning_To_v1_InstanceProvisioning(&in.InstanceProvisioning, &out.InstanceProvisioning, s); err != nil {
		return err
	}
	if err := Convert_prd_UserProvidedService_To_v1_UserProvidedService(&in.UserProvidedService, &out.UserProvidedService, s); err != nil {
		return err
	}
	out.Binding = *(*[]InstanceBinding)(unsafe.Pointer(&in.Binding))
	out.Bound = in.Bound
	out.InstanceID = in.InstanceID
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	return nil
}

// Convert_prd_BackingServiceInstanceSpec_To_v1_BackingServiceInstanceSpec is an autogenerated conversion function.
func Convert_prd_BackingServiceInstanceSpec_To_v1_BackingServiceInstanceSpec(in *prd.BackingServiceInstanceSpec, out *BackingServiceInstanceSpec, s conversion.Scope) error {
	return autoConvert_prd_BackingServiceInstanceSpec_To_v1_BackingServiceInstanceSpec(in, out, s)
}

func autoConvert_v1_BackingServiceInstanceStatus_To_prd_BackingServiceInstanceStatus(in *BackingServiceInstanceStatus, out *prd.BackingServiceInstanceStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	out.Action = in.Action
	out.Patch = in.Patch
	out.Reason = in.Reason
	out.LastOperation = (*prd.LastOperation)(unsafe.Pointer(in.LastOperation))
	return nil
}

// Convert_v1_BackingServiceInstanceStatus_To_prd_BackingServiceInstanceStatus is an autogenerated conversion function.
func Convert_v1_BackingServiceInstanceStatus_To_prd_BackingServiceInstanceStatus(in *BackingServiceInstanceStatus, out *prd.BackingServiceInstanceStatus, s conversion.Scope) error {
	return autoConvert_v1_BackingServiceInstanceStatus_To_prd_BackingServiceInstanceStatus(in, out, s)
}

func autoConvert_prd_BackingServiceInstanceStatus_To_v1_BackingServiceInstanceStatus(in *prd.BackingServiceInstanceStatus, out *BackingServiceInstanceStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	out.Action = in.Action
	out.Patch = in.Patch
	out.Reason = in.Reason
	out.LastOperation = (*LastOperation)(unsafe.Pointer(in.LastOperation))
	return nil
}

// Convert_prd_BackingServiceInstanceStatus_To_v1_BackingServiceInstanceStatus is an autogenerated conversion function.
func Convert_prd_BackingServiceInstanceStatus_To_v1_BackingServiceInstanceStatus(in *prd.BackingServiceInstanceStatus, out *BackingServiceInstanceStatus, s conversion.Scope) error {
	return autoConvert_prd_BackingServiceInstanceStatus_To_v1_BackingServiceInstanceStatus(in, out, s)
}

func autoConvert_v1_BackingServiceInstanceStatusStrategy_To_prd_BackingServiceInstanceStatusStrategy(in *BackingServiceInstanceStatusStrategy, out *prd.BackingServiceInstanceStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1_BackingServiceInstanceStatusStrategy_To_prd_BackingServiceInstanceStatusStrategy is an autogenerated conversion function.
func Convert_v1_BackingServiceInstanceStatusStrategy_To_prd_BackingServiceInstanceStatusStrategy(in *BackingServiceInstanceStatusStrategy, out *prd.BackingServiceInstanceStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1_BackingServiceInstanceStatusStrategy_To_prd_BackingServiceInstanceStatusStrategy(in, out, s)
}

func autoConvert_prd_BackingServiceInstanceStatusStrategy_To_v1_BackingServiceInstanceStatusStrategy(in *prd.BackingServiceInstanceStatusStrategy, out *BackingServiceInstanceStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_prd_BackingServiceInstanceStatusStrategy_To_v1_BackingServiceInstanceStatusStrategy is an autogenerated conversion function.
func Convert_prd_BackingServiceInstanceStatusStrategy_To_v1_BackingServiceInstanceStatusStrategy(in *prd.BackingServiceInstanceStatusStrategy, out *BackingServiceInstanceStatusStrategy, s conversion.Scope) error {
	return autoConvert_prd_BackingServiceInstanceStatusStrategy_To_v1_BackingServiceInstanceStatusStrategy(in, out, s)
}

func autoConvert_v1_BackingServiceInstanceStrategy_To_prd_BackingServiceInstanceStrategy(in *BackingServiceInstanceStrategy, out *prd.BackingServiceInstanceStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1_BackingServiceInstanceStrategy_To_prd_BackingServiceInstanceStrategy is an autogenerated conversion function.
func Convert_v1_BackingServiceInstanceStrategy_To_prd_BackingServiceInstanceStrategy(in *BackingServiceInstanceStrategy, out *prd.BackingServiceInstanceStrategy, s conversion.Scope) error {
	return autoConvert_v1_BackingServiceInstanceStrategy_To_prd_BackingServiceInstanceStrategy(in, out, s)
}

func autoConvert_prd_BackingServiceInstanceStrategy_To_v1_BackingServiceInstanceStrategy(in *prd.BackingServiceInstanceStrategy, out *BackingServiceInstanceStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_prd_BackingServiceInstanceStrategy_To_v1_BackingServiceInstanceStrategy is an autogenerated conversion function.
func Convert_prd_BackingServiceInstanceStrategy_To_v1_BackingServiceInstanceStrategy(in *prd.BackingServiceInstanceStrategy, out *BackingServiceInstanceStrategy, s conversion.Scope) error {
	return autoConvert_prd_BackingServiceInstanceStrategy_To_v1_BackingServiceInstanceStrategy(in, out, s)
}

func autoConvert_v1_BackingServiceList_To_prd_BackingServiceList(in *BackingServiceList, out *prd.BackingServiceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]prd.BackingService)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_BackingServiceList_To_prd_BackingServiceList is an autogenerated conversion function.
func Convert_v1_BackingServiceList_To_prd_BackingServiceList(in *BackingServiceList, out *prd.BackingServiceList, s conversion.Scope) error {
	return autoConvert_v1_BackingServiceList_To_prd_BackingServiceList(in, out, s)
}

func autoConvert_prd_BackingServiceList_To_v1_BackingServiceList(in *prd.BackingServiceList, out *BackingServiceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]BackingService)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_prd_BackingServiceList_To_v1_BackingServiceList is an autogenerated conversion function.
func Convert_prd_BackingServiceList_To_v1_BackingServiceList(in *prd.BackingServiceList, out *BackingServiceList, s conversion.Scope) error {
	return autoConvert_prd_BackingServiceList_To_v1_BackingServiceList(in, out, s)
}

func autoConvert_v1_BackingServiceSpec_To_prd_BackingServiceSpec(in *BackingServiceSpec, out *prd.BackingServiceSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Id = in.Id
	out.Description = in.Description
	out.Bindable = in.Bindable
	out.PlanUpdateable = in.PlanUpdateable
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	out.Requires = *(*[]string)(unsafe.Pointer(&in.Requires))
	out.Metadata = *(*map[string]string)(unsafe.Pointer(&in.Metadata))
	out.Plans = *(*[]prd.ServicePlan)(unsafe.Pointer(&in.Plans))
	out.DashboardClient = *(*map[string]string)(unsafe.Pointer(&in.DashboardClient))
	return nil
}

// Convert_v1_BackingServiceSpec_To_prd_BackingServiceSpec is an autogenerated conversion function.
func Convert_v1_BackingServiceSpec_To_prd_BackingServiceSpec(in *BackingServiceSpec, out *prd.BackingServiceSpec, s conversion.Scope) error {
	return autoConvert_v1_BackingServiceSpec_To_prd_BackingServiceSpec(in, out, s)
}

func autoConvert_prd_BackingServiceSpec_To_v1_BackingServiceSpec(in *prd.BackingServiceSpec, out *BackingServiceSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Id = in.Id
	out.Description = in.Description
	out.Bindable = in.Bindable
	out.PlanUpdateable = in.PlanUpdateable
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	out.Requires = *(*[]string)(unsafe.Pointer(&in.Requires))
	out.Metadata = *(*map[string]string)(unsafe.Pointer(&in.Metadata))
	out.Plans = *(*[]ServicePlan)(unsafe.Pointer(&in.Plans))
	out.DashboardClient = *(*map[string]string)(unsafe.Pointer(&in.DashboardClient))
	return nil
}

// Convert_prd_BackingServiceSpec_To_v1_BackingServiceSpec is an autogenerated conversion function.
func Convert_prd_BackingServiceSpec_To_v1_BackingServiceSpec(in *prd.BackingServiceSpec, out *BackingServiceSpec, s conversion.Scope) error {
	return autoConvert_prd_BackingServiceSpec_To_v1_BackingServiceSpec(in, out, s)
}

func autoConvert_v1_BackingServiceStatus_To_prd_BackingServiceStatus(in *BackingServiceStatus, out *prd.BackingServiceStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	return nil
}

// Convert_v1_BackingServiceStatus_To_prd_BackingServiceStatus is an autogenerated conversion function.
func Convert_v1_BackingServiceStatus_To_prd_BackingServiceStatus(in *BackingServiceStatus, out *prd.BackingServiceStatus, s conversion.Scope) error {
	return autoConvert_v1_BackingServiceStatus_To_prd_BackingServiceStatus(in, out, s)
}

func autoConvert_prd_BackingServiceStatus_To_v1_BackingServiceStatus(in *prd.BackingServiceStatus, out *BackingServiceStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	return nil
}

// Convert_prd_BackingServiceStatus_To_v1_BackingServiceStatus is an autogenerated conversion function.
func Convert_prd_BackingServiceStatus_To_v1_BackingServiceStatus(in *prd.BackingServiceStatus, out *BackingServiceStatus, s conversion.Scope) error {
	return autoConvert_prd_BackingServiceStatus_To_v1_BackingServiceStatus(in, out, s)
}

func autoConvert_v1_BackingServiceStatusStrategy_To_prd_BackingServiceStatusStrategy(in *BackingServiceStatusStrategy, out *prd.BackingServiceStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1_BackingServiceStatusStrategy_To_prd_BackingServiceStatusStrategy is an autogenerated conversion function.
func Convert_v1_BackingServiceStatusStrategy_To_prd_BackingServiceStatusStrategy(in *BackingServiceStatusStrategy, out *prd.BackingServiceStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1_BackingServiceStatusStrategy_To_prd_BackingServiceStatusStrategy(in, out, s)
}

func autoConvert_prd_BackingServiceStatusStrategy_To_v1_BackingServiceStatusStrategy(in *prd.BackingServiceStatusStrategy, out *BackingServiceStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_prd_BackingServiceStatusStrategy_To_v1_BackingServiceStatusStrategy is an autogenerated conversion function.
func Convert_prd_BackingServiceStatusStrategy_To_v1_BackingServiceStatusStrategy(in *prd.BackingServiceStatusStrategy, out *BackingServiceStatusStrategy, s conversion.Scope) error {
	return autoConvert_prd_BackingServiceStatusStrategy_To_v1_BackingServiceStatusStrategy(in, out, s)
}

func autoConvert_v1_BackingServiceStrategy_To_prd_BackingServiceStrategy(in *BackingServiceStrategy, out *prd.BackingServiceStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1_BackingServiceStrategy_To_prd_BackingServiceStrategy is an autogenerated conversion function.
func Convert_v1_BackingServiceStrategy_To_prd_BackingServiceStrategy(in *BackingServiceStrategy, out *prd.BackingServiceStrategy, s conversion.Scope) error {
	return autoConvert_v1_BackingServiceStrategy_To_prd_BackingServiceStrategy(in, out, s)
}

func autoConvert_prd_BackingServiceStrategy_To_v1_BackingServiceStrategy(in *prd.BackingServiceStrategy, out *BackingServiceStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_prd_BackingServiceStrategy_To_v1_BackingServiceStrategy is an autogenerated conversion function.
func Convert_prd_BackingServiceStrategy_To_v1_BackingServiceStrategy(in *prd.BackingServiceStrategy, out *BackingServiceStrategy, s conversion.Scope) error {
	return autoConvert_prd_BackingServiceStrategy_To_v1_BackingServiceStrategy(in, out, s)
}

func autoConvert_v1_Binding_To_prd_Binding(in *Binding, out *prd.Binding, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.BindKind = in.BindKind
	out.BindResourceVersion = in.BindResourceVersion
	out.ResourceName = in.ResourceName
	out.Parameters = *(*map[string]string)(unsafe.Pointer(&in.Parameters))
	return nil
}

// Convert_v1_Binding_To_prd_Binding is an autogenerated conversion function.
func Convert_v1_Binding_To_prd_Binding(in *Binding, out *prd.Binding, s conversion.Scope) error {
	return autoConvert_v1_Binding_To_prd_Binding(in, out, s)
}

func autoConvert_prd_Binding_To_v1_Binding(in *prd.Binding, out *Binding, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.BindKind = in.BindKind
	out.BindResourceVersion = in.BindResourceVersion
	out.ResourceName = in.ResourceName
	out.Parameters = *(*map[string]string)(unsafe.Pointer(&in.Parameters))
	return nil
}

// Convert_prd_Binding_To_v1_Binding is an autogenerated conversion function.
func Convert_prd_Binding_To_v1_Binding(in *prd.Binding, out *Binding, s conversion.Scope) error {
	return autoConvert_prd_Binding_To_v1_Binding(in, out, s)
}

func autoConvert_v1_BindingList_To_prd_BindingList(in *BindingList, out *prd.BindingList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]prd.Binding)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_BindingList_To_prd_BindingList is an autogenerated conversion function.
func Convert_v1_BindingList_To_prd_BindingList(in *BindingList, out *prd.BindingList, s conversion.Scope) error {
	return autoConvert_v1_BindingList_To_prd_BindingList(in, out, s)
}

func autoConvert_prd_BindingList_To_v1_BindingList(in *prd.BindingList, out *BindingList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Binding)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_prd_BindingList_To_v1_BindingList is an autogenerated conversion function.
func Convert_prd_BindingList_To_v1_BindingList(in *prd.BindingList, out *BindingList, s conversion.Scope) error {
	return autoConvert_prd_BindingList_To_v1_BindingList(in, out, s)
}

func autoConvert_v1_CustomizeSpec_To_prd_CustomizeSpec(in *CustomizeSpec, out *prd.CustomizeSpec, s conversion.Scope) error {
	out.Default = in.Default
	out.Max = in.Max
	out.Price = in.Price
	out.Step = in.Step
	out.Unit = in.Unit
	out.Desc = in.Desc
	return nil
}

// Convert_v1_CustomizeSpec_To_prd_CustomizeSpec is an autogenerated conversion function.
func Convert_v1_CustomizeSpec_To_prd_CustomizeSpec(in *CustomizeSpec, out *prd.CustomizeSpec, s conversion.Scope) error {
	return autoConvert_v1_CustomizeSpec_To_prd_CustomizeSpec(in, out, s)
}

func autoConvert_prd_CustomizeSpec_To_v1_CustomizeSpec(in *prd.CustomizeSpec, out *CustomizeSpec, s conversion.Scope) error {
	out.Default = in.Default
	out.Max = in.Max
	out.Price = in.Price
	out.Step = in.Step
	out.Unit = in.Unit
	out.Desc = in.Desc
	return nil
}

// Convert_prd_CustomizeSpec_To_v1_CustomizeSpec is an autogenerated conversion function.
func Convert_prd_CustomizeSpec_To_v1_CustomizeSpec(in *prd.CustomizeSpec, out *CustomizeSpec, s conversion.Scope) error {
	return autoConvert_prd_CustomizeSpec_To_v1_CustomizeSpec(in, out, s)
}

func autoConvert_v1_InstanceBinding_To_prd_InstanceBinding(in *InstanceBinding, out *prd.InstanceBinding, s conversion.Scope) error {
	out.BoundTime = (*meta.Time)(unsafe.Pointer(in.BoundTime))
	out.BindUuid = in.BindUuid
	out.BindDeploymentConfig = in.BindDeploymentConfig
	out.BindHadoopUser = in.BindHadoopUser
	out.Credentials = *(*map[string]string)(unsafe.Pointer(&in.Credentials))
	return nil
}

// Convert_v1_InstanceBinding_To_prd_InstanceBinding is an autogenerated conversion function.
func Convert_v1_InstanceBinding_To_prd_InstanceBinding(in *InstanceBinding, out *prd.InstanceBinding, s conversion.Scope) error {
	return autoConvert_v1_InstanceBinding_To_prd_InstanceBinding(in, out, s)
}

func autoConvert_prd_InstanceBinding_To_v1_InstanceBinding(in *prd.InstanceBinding, out *InstanceBinding, s conversion.Scope) error {
	out.BoundTime = (*meta_v1.Time)(unsafe.Pointer(in.BoundTime))
	out.BindUuid = in.BindUuid
	out.BindDeploymentConfig = in.BindDeploymentConfig
	out.BindHadoopUser = in.BindHadoopUser
	out.Credentials = *(*map[string]string)(unsafe.Pointer(&in.Credentials))
	return nil
}

// Convert_prd_InstanceBinding_To_v1_InstanceBinding is an autogenerated conversion function.
func Convert_prd_InstanceBinding_To_v1_InstanceBinding(in *prd.InstanceBinding, out *InstanceBinding, s conversion.Scope) error {
	return autoConvert_prd_InstanceBinding_To_v1_InstanceBinding(in, out, s)
}

func autoConvert_v1_InstanceProvisioning_To_prd_InstanceProvisioning(in *InstanceProvisioning, out *prd.InstanceProvisioning, s conversion.Scope) error {
	out.DashboardUrl = in.DashboardUrl
	out.BackingServiceName = in.BackingServiceName
	out.BackingServiceSpecID = in.BackingServiceSpecID
	out.BackingServicePlanGuid = in.BackingServicePlanGuid
	out.BackingServicePlanName = in.BackingServicePlanName
	out.Parameters = *(*map[string]string)(unsafe.Pointer(&in.Parameters))
	out.Creds = *(*map[string]string)(unsafe.Pointer(&in.Creds))
	out.Accesses = *(*map[string][]string)(unsafe.Pointer(&in.Accesses))
	return nil
}

// Convert_v1_InstanceProvisioning_To_prd_InstanceProvisioning is an autogenerated conversion function.
func Convert_v1_InstanceProvisioning_To_prd_InstanceProvisioning(in *InstanceProvisioning, out *prd.InstanceProvisioning, s conversion.Scope) error {
	return autoConvert_v1_InstanceProvisioning_To_prd_InstanceProvisioning(in, out, s)
}

func autoConvert_prd_InstanceProvisioning_To_v1_InstanceProvisioning(in *prd.InstanceProvisioning, out *InstanceProvisioning, s conversion.Scope) error {
	out.DashboardUrl = in.DashboardUrl
	out.BackingServiceName = in.BackingServiceName
	out.BackingServiceSpecID = in.BackingServiceSpecID
	out.BackingServicePlanGuid = in.BackingServicePlanGuid
	out.BackingServicePlanName = in.BackingServicePlanName
	out.Parameters = *(*map[string]string)(unsafe.Pointer(&in.Parameters))
	out.Creds = *(*map[string]string)(unsafe.Pointer(&in.Creds))
	out.Accesses = *(*map[string][]string)(unsafe.Pointer(&in.Accesses))
	return nil
}

// Convert_prd_InstanceProvisioning_To_v1_InstanceProvisioning is an autogenerated conversion function.
func Convert_prd_InstanceProvisioning_To_v1_InstanceProvisioning(in *prd.InstanceProvisioning, out *InstanceProvisioning, s conversion.Scope) error {
	return autoConvert_prd_InstanceProvisioning_To_v1_InstanceProvisioning(in, out, s)
}

func autoConvert_v1_LastOperation_To_prd_LastOperation(in *LastOperation, out *prd.LastOperation, s conversion.Scope) error {
	out.State = in.State
	out.Description = in.Description
	out.AsyncPollIntervalSeconds = in.AsyncPollIntervalSeconds
	return nil
}

// Convert_v1_LastOperation_To_prd_LastOperation is an autogenerated conversion function.
func Convert_v1_LastOperation_To_prd_LastOperation(in *LastOperation, out *prd.LastOperation, s conversion.Scope) error {
	return autoConvert_v1_LastOperation_To_prd_LastOperation(in, out, s)
}

func autoConvert_prd_LastOperation_To_v1_LastOperation(in *prd.LastOperation, out *LastOperation, s conversion.Scope) error {
	out.State = in.State
	out.Description = in.Description
	out.AsyncPollIntervalSeconds = in.AsyncPollIntervalSeconds
	return nil
}

// Convert_prd_LastOperation_To_v1_LastOperation is an autogenerated conversion function.
func Convert_prd_LastOperation_To_v1_LastOperation(in *prd.LastOperation, out *LastOperation, s conversion.Scope) error {
	return autoConvert_prd_LastOperation_To_v1_LastOperation(in, out, s)
}

func autoConvert_v1_ServiceBroker_To_prd_ServiceBroker(in *ServiceBroker, out *prd.ServiceBroker, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_ServiceBrokerSpec_To_prd_ServiceBrokerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_ServiceBrokerStatus_To_prd_ServiceBrokerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_ServiceBroker_To_prd_ServiceBroker is an autogenerated conversion function.
func Convert_v1_ServiceBroker_To_prd_ServiceBroker(in *ServiceBroker, out *prd.ServiceBroker, s conversion.Scope) error {
	return autoConvert_v1_ServiceBroker_To_prd_ServiceBroker(in, out, s)
}

func autoConvert_prd_ServiceBroker_To_v1_ServiceBroker(in *prd.ServiceBroker, out *ServiceBroker, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_prd_ServiceBrokerSpec_To_v1_ServiceBrokerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_prd_ServiceBrokerStatus_To_v1_ServiceBrokerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_prd_ServiceBroker_To_v1_ServiceBroker is an autogenerated conversion function.
func Convert_prd_ServiceBroker_To_v1_ServiceBroker(in *prd.ServiceBroker, out *ServiceBroker, s conversion.Scope) error {
	return autoConvert_prd_ServiceBroker_To_v1_ServiceBroker(in, out, s)
}

func autoConvert_v1_ServiceBrokerList_To_prd_ServiceBrokerList(in *ServiceBrokerList, out *prd.ServiceBrokerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]prd.ServiceBroker)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_ServiceBrokerList_To_prd_ServiceBrokerList is an autogenerated conversion function.
func Convert_v1_ServiceBrokerList_To_prd_ServiceBrokerList(in *ServiceBrokerList, out *prd.ServiceBrokerList, s conversion.Scope) error {
	return autoConvert_v1_ServiceBrokerList_To_prd_ServiceBrokerList(in, out, s)
}

func autoConvert_prd_ServiceBrokerList_To_v1_ServiceBrokerList(in *prd.ServiceBrokerList, out *ServiceBrokerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ServiceBroker)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_prd_ServiceBrokerList_To_v1_ServiceBrokerList is an autogenerated conversion function.
func Convert_prd_ServiceBrokerList_To_v1_ServiceBrokerList(in *prd.ServiceBrokerList, out *ServiceBrokerList, s conversion.Scope) error {
	return autoConvert_prd_ServiceBrokerList_To_v1_ServiceBrokerList(in, out, s)
}

func autoConvert_v1_ServiceBrokerSpec_To_prd_ServiceBrokerSpec(in *ServiceBrokerSpec, out *prd.ServiceBrokerSpec, s conversion.Scope) error {
	out.Url = in.Url
	out.Name = in.Name
	out.UserName = in.UserName
	out.Password = in.Password
	out.Finalizers = *(*[]core_v1.FinalizerName)(unsafe.Pointer(&in.Finalizers))
	return nil
}

// Convert_v1_ServiceBrokerSpec_To_prd_ServiceBrokerSpec is an autogenerated conversion function.
func Convert_v1_ServiceBrokerSpec_To_prd_ServiceBrokerSpec(in *ServiceBrokerSpec, out *prd.ServiceBrokerSpec, s conversion.Scope) error {
	return autoConvert_v1_ServiceBrokerSpec_To_prd_ServiceBrokerSpec(in, out, s)
}

func autoConvert_prd_ServiceBrokerSpec_To_v1_ServiceBrokerSpec(in *prd.ServiceBrokerSpec, out *ServiceBrokerSpec, s conversion.Scope) error {
	out.Url = in.Url
	out.Name = in.Name
	out.UserName = in.UserName
	out.Password = in.Password
	out.Finalizers = *(*[]core_v1.FinalizerName)(unsafe.Pointer(&in.Finalizers))
	return nil
}

// Convert_prd_ServiceBrokerSpec_To_v1_ServiceBrokerSpec is an autogenerated conversion function.
func Convert_prd_ServiceBrokerSpec_To_v1_ServiceBrokerSpec(in *prd.ServiceBrokerSpec, out *ServiceBrokerSpec, s conversion.Scope) error {
	return autoConvert_prd_ServiceBrokerSpec_To_v1_ServiceBrokerSpec(in, out, s)
}

func autoConvert_v1_ServiceBrokerStatus_To_prd_ServiceBrokerStatus(in *ServiceBrokerStatus, out *prd.ServiceBrokerStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	return nil
}

// Convert_v1_ServiceBrokerStatus_To_prd_ServiceBrokerStatus is an autogenerated conversion function.
func Convert_v1_ServiceBrokerStatus_To_prd_ServiceBrokerStatus(in *ServiceBrokerStatus, out *prd.ServiceBrokerStatus, s conversion.Scope) error {
	return autoConvert_v1_ServiceBrokerStatus_To_prd_ServiceBrokerStatus(in, out, s)
}

func autoConvert_prd_ServiceBrokerStatus_To_v1_ServiceBrokerStatus(in *prd.ServiceBrokerStatus, out *ServiceBrokerStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	return nil
}

// Convert_prd_ServiceBrokerStatus_To_v1_ServiceBrokerStatus is an autogenerated conversion function.
func Convert_prd_ServiceBrokerStatus_To_v1_ServiceBrokerStatus(in *prd.ServiceBrokerStatus, out *ServiceBrokerStatus, s conversion.Scope) error {
	return autoConvert_prd_ServiceBrokerStatus_To_v1_ServiceBrokerStatus(in, out, s)
}

func autoConvert_v1_ServiceBrokerStatusStrategy_To_prd_ServiceBrokerStatusStrategy(in *ServiceBrokerStatusStrategy, out *prd.ServiceBrokerStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1_ServiceBrokerStatusStrategy_To_prd_ServiceBrokerStatusStrategy is an autogenerated conversion function.
func Convert_v1_ServiceBrokerStatusStrategy_To_prd_ServiceBrokerStatusStrategy(in *ServiceBrokerStatusStrategy, out *prd.ServiceBrokerStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1_ServiceBrokerStatusStrategy_To_prd_ServiceBrokerStatusStrategy(in, out, s)
}

func autoConvert_prd_ServiceBrokerStatusStrategy_To_v1_ServiceBrokerStatusStrategy(in *prd.ServiceBrokerStatusStrategy, out *ServiceBrokerStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_prd_ServiceBrokerStatusStrategy_To_v1_ServiceBrokerStatusStrategy is an autogenerated conversion function.
func Convert_prd_ServiceBrokerStatusStrategy_To_v1_ServiceBrokerStatusStrategy(in *prd.ServiceBrokerStatusStrategy, out *ServiceBrokerStatusStrategy, s conversion.Scope) error {
	return autoConvert_prd_ServiceBrokerStatusStrategy_To_v1_ServiceBrokerStatusStrategy(in, out, s)
}

func autoConvert_v1_ServiceBrokerStrategy_To_prd_ServiceBrokerStrategy(in *ServiceBrokerStrategy, out *prd.ServiceBrokerStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1_ServiceBrokerStrategy_To_prd_ServiceBrokerStrategy is an autogenerated conversion function.
func Convert_v1_ServiceBrokerStrategy_To_prd_ServiceBrokerStrategy(in *ServiceBrokerStrategy, out *prd.ServiceBrokerStrategy, s conversion.Scope) error {
	return autoConvert_v1_ServiceBrokerStrategy_To_prd_ServiceBrokerStrategy(in, out, s)
}

func autoConvert_prd_ServiceBrokerStrategy_To_v1_ServiceBrokerStrategy(in *prd.ServiceBrokerStrategy, out *ServiceBrokerStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_prd_ServiceBrokerStrategy_To_v1_ServiceBrokerStrategy is an autogenerated conversion function.
func Convert_prd_ServiceBrokerStrategy_To_v1_ServiceBrokerStrategy(in *prd.ServiceBrokerStrategy, out *ServiceBrokerStrategy, s conversion.Scope) error {
	return autoConvert_prd_ServiceBrokerStrategy_To_v1_ServiceBrokerStrategy(in, out, s)
}

func autoConvert_v1_ServicePlan_To_prd_ServicePlan(in *ServicePlan, out *prd.ServicePlan, s conversion.Scope) error {
	out.Name = in.Name
	out.Id = in.Id
	out.Description = in.Description
	if err := Convert_v1_ServicePlanMetadata_To_prd_ServicePlanMetadata(&in.Metadata, &out.Metadata, s); err != nil {
		return err
	}
	out.Free = in.Free
	return nil
}

// Convert_v1_ServicePlan_To_prd_ServicePlan is an autogenerated conversion function.
func Convert_v1_ServicePlan_To_prd_ServicePlan(in *ServicePlan, out *prd.ServicePlan, s conversion.Scope) error {
	return autoConvert_v1_ServicePlan_To_prd_ServicePlan(in, out, s)
}

func autoConvert_prd_ServicePlan_To_v1_ServicePlan(in *prd.ServicePlan, out *ServicePlan, s conversion.Scope) error {
	out.Name = in.Name
	out.Id = in.Id
	out.Description = in.Description
	if err := Convert_prd_ServicePlanMetadata_To_v1_ServicePlanMetadata(&in.Metadata, &out.Metadata, s); err != nil {
		return err
	}
	out.Free = in.Free
	return nil
}

// Convert_prd_ServicePlan_To_v1_ServicePlan is an autogenerated conversion function.
func Convert_prd_ServicePlan_To_v1_ServicePlan(in *prd.ServicePlan, out *ServicePlan, s conversion.Scope) error {
	return autoConvert_prd_ServicePlan_To_v1_ServicePlan(in, out, s)
}

func autoConvert_v1_ServicePlanCost_To_prd_ServicePlanCost(in *ServicePlanCost, out *prd.ServicePlanCost, s conversion.Scope) error {
	out.Amount = *(*map[string]float64)(unsafe.Pointer(&in.Amount))
	out.Unit = in.Unit
	return nil
}

// Convert_v1_ServicePlanCost_To_prd_ServicePlanCost is an autogenerated conversion function.
func Convert_v1_ServicePlanCost_To_prd_ServicePlanCost(in *ServicePlanCost, out *prd.ServicePlanCost, s conversion.Scope) error {
	return autoConvert_v1_ServicePlanCost_To_prd_ServicePlanCost(in, out, s)
}

func autoConvert_prd_ServicePlanCost_To_v1_ServicePlanCost(in *prd.ServicePlanCost, out *ServicePlanCost, s conversion.Scope) error {
	out.Amount = *(*map[string]float64)(unsafe.Pointer(&in.Amount))
	out.Unit = in.Unit
	return nil
}

// Convert_prd_ServicePlanCost_To_v1_ServicePlanCost is an autogenerated conversion function.
func Convert_prd_ServicePlanCost_To_v1_ServicePlanCost(in *prd.ServicePlanCost, out *ServicePlanCost, s conversion.Scope) error {
	return autoConvert_prd_ServicePlanCost_To_v1_ServicePlanCost(in, out, s)
}

func autoConvert_v1_ServicePlanMetadata_To_prd_ServicePlanMetadata(in *ServicePlanMetadata, out *prd.ServicePlanMetadata, s conversion.Scope) error {
	out.Bullets = *(*[]string)(unsafe.Pointer(&in.Bullets))
	out.Costs = *(*[]prd.ServicePlanCost)(unsafe.Pointer(&in.Costs))
	out.DisplayName = in.DisplayName
	out.Customize = *(*map[string]prd.CustomizeSpec)(unsafe.Pointer(&in.Customize))
	return nil
}

// Convert_v1_ServicePlanMetadata_To_prd_ServicePlanMetadata is an autogenerated conversion function.
func Convert_v1_ServicePlanMetadata_To_prd_ServicePlanMetadata(in *ServicePlanMetadata, out *prd.ServicePlanMetadata, s conversion.Scope) error {
	return autoConvert_v1_ServicePlanMetadata_To_prd_ServicePlanMetadata(in, out, s)
}

func autoConvert_prd_ServicePlanMetadata_To_v1_ServicePlanMetadata(in *prd.ServicePlanMetadata, out *ServicePlanMetadata, s conversion.Scope) error {
	out.Bullets = *(*[]string)(unsafe.Pointer(&in.Bullets))
	out.Costs = *(*[]ServicePlanCost)(unsafe.Pointer(&in.Costs))
	out.DisplayName = in.DisplayName
	out.Customize = *(*map[string]CustomizeSpec)(unsafe.Pointer(&in.Customize))
	return nil
}

// Convert_prd_ServicePlanMetadata_To_v1_ServicePlanMetadata is an autogenerated conversion function.
func Convert_prd_ServicePlanMetadata_To_v1_ServicePlanMetadata(in *prd.ServicePlanMetadata, out *ServicePlanMetadata, s conversion.Scope) error {
	return autoConvert_prd_ServicePlanMetadata_To_v1_ServicePlanMetadata(in, out, s)
}

func autoConvert_v1_UserProvidedService_To_prd_UserProvidedService(in *UserProvidedService, out *prd.UserProvidedService, s conversion.Scope) error {
	out.Credentials = *(*map[string]string)(unsafe.Pointer(&in.Credentials))
	return nil
}

// Convert_v1_UserProvidedService_To_prd_UserProvidedService is an autogenerated conversion function.
func Convert_v1_UserProvidedService_To_prd_UserProvidedService(in *UserProvidedService, out *prd.UserProvidedService, s conversion.Scope) error {
	return autoConvert_v1_UserProvidedService_To_prd_UserProvidedService(in, out, s)
}

func autoConvert_prd_UserProvidedService_To_v1_UserProvidedService(in *prd.UserProvidedService, out *UserProvidedService, s conversion.Scope) error {
	out.Credentials = *(*map[string]string)(unsafe.Pointer(&in.Credentials))
	return nil
}

// Convert_prd_UserProvidedService_To_v1_UserProvidedService is an autogenerated conversion function.
func Convert_prd_UserProvidedService_To_v1_UserProvidedService(in *prd.UserProvidedService, out *UserProvidedService, s conversion.Scope) error {
	return autoConvert_prd_UserProvidedService_To_v1_UserProvidedService(in, out, s)
}
