/*
@asiainfo.com
*/

// This file was automatically generated by lister-gen

package internalversion

// BackingServiceListerExpansion allows custom methods to be added to
// BackingServiceLister.
type BackingServiceListerExpansion interface{}

// BackingServiceInstanceListerExpansion allows custom methods to be added to
// BackingServiceInstanceLister.
type BackingServiceInstanceListerExpansion interface{}

// BackingServiceInstanceNamespaceListerExpansion allows custom methods to be added to
// BackingServiceInstanceNamespaceLister.
type BackingServiceInstanceNamespaceListerExpansion interface{}

// ServiceBrokerListerExpansion allows custom methods to be added to
// ServiceBrokerLister.
type ServiceBrokerListerExpansion interface{}
