/*
@asiainfo.com
*/

// This file was automatically generated by informer-gen

package v1

import (
	prd_v1 "github.com/asiainfoldp/apiserver-servicebroker/pkg/apis/prd/v1"
	clientset "github.com/asiainfoldp/apiserver-servicebroker/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/asiainfoldp/apiserver-servicebroker/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1 "github.com/asiainfoldp/apiserver-servicebroker/pkg/client/listers_generated/prd/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// BackingServiceInstanceInformer provides access to a shared informer and lister for
// BackingServiceInstances.
type BackingServiceInstanceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.BackingServiceInstanceLister
}

type backingServiceInstanceInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewBackingServiceInstanceInformer constructs a new informer for BackingServiceInstance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBackingServiceInstanceInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				return client.PrdV1().BackingServiceInstances(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				return client.PrdV1().BackingServiceInstances(namespace).Watch(options)
			},
		},
		&prd_v1.BackingServiceInstance{},
		resyncPeriod,
		indexers,
	)
}

func defaultBackingServiceInstanceInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewBackingServiceInstanceInformer(client, meta_v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *backingServiceInstanceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&prd_v1.BackingServiceInstance{}, defaultBackingServiceInstanceInformer)
}

func (f *backingServiceInstanceInformer) Lister() v1.BackingServiceInstanceLister {
	return v1.NewBackingServiceInstanceLister(f.Informer().GetIndexer())
}
