/*
@asiainfo.com
*/

// This file was automatically generated by informer-gen

package v1

import (
	prd_v1 "github.com/asiainfoldp/apiserver-servicebroker/pkg/apis/prd/v1"
	clientset "github.com/asiainfoldp/apiserver-servicebroker/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/asiainfoldp/apiserver-servicebroker/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1 "github.com/asiainfoldp/apiserver-servicebroker/pkg/client/listers_generated/prd/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// BackingServiceInformer provides access to a shared informer and lister for
// BackingServices.
type BackingServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.BackingServiceLister
}

type backingServiceInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewBackingServiceInformer constructs a new informer for BackingService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBackingServiceInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				return client.PrdV1().BackingServices().List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				return client.PrdV1().BackingServices().Watch(options)
			},
		},
		&prd_v1.BackingService{},
		resyncPeriod,
		indexers,
	)
}

func defaultBackingServiceInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewBackingServiceInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *backingServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&prd_v1.BackingService{}, defaultBackingServiceInformer)
}

func (f *backingServiceInformer) Lister() v1.BackingServiceLister {
	return v1.NewBackingServiceLister(f.Informer().GetIndexer())
}
