/*
@asiainfo.com
*/

// This file was automatically generated by informer-gen

package v1

import (
	prd_v1 "github.com/asiainfoldp/apiserver-servicebroker/pkg/apis/prd/v1"
	clientset "github.com/asiainfoldp/apiserver-servicebroker/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/asiainfoldp/apiserver-servicebroker/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1 "github.com/asiainfoldp/apiserver-servicebroker/pkg/client/listers_generated/prd/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// ServiceBrokerInformer provides access to a shared informer and lister for
// ServiceBrokers.
type ServiceBrokerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ServiceBrokerLister
}

type serviceBrokerInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewServiceBrokerInformer constructs a new informer for ServiceBroker type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewServiceBrokerInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				return client.PrdV1().ServiceBrokers().List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				return client.PrdV1().ServiceBrokers().Watch(options)
			},
		},
		&prd_v1.ServiceBroker{},
		resyncPeriod,
		indexers,
	)
}

func defaultServiceBrokerInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewServiceBrokerInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *serviceBrokerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&prd_v1.ServiceBroker{}, defaultServiceBrokerInformer)
}

func (f *serviceBrokerInformer) Lister() v1.ServiceBrokerLister {
	return v1.NewServiceBrokerLister(f.Informer().GetIndexer())
}
