/*
@asiainfo.com
*/

// This file was automatically generated by informer-gen

package internalversion

import (
	prd "github.com/asiainfoldp/apiserver-servicebroker/pkg/apis/prd"
	internalclientset "github.com/asiainfoldp/apiserver-servicebroker/pkg/client/clientset_generated/internalclientset"
	internalinterfaces "github.com/asiainfoldp/apiserver-servicebroker/pkg/client/informers_generated/internalversion/internalinterfaces"
	internalversion "github.com/asiainfoldp/apiserver-servicebroker/pkg/client/listers_generated/prd/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// BackingServiceInformer provides access to a shared informer and lister for
// BackingServices.
type BackingServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.BackingServiceLister
}

type backingServiceInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewBackingServiceInformer constructs a new informer for BackingService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBackingServiceInformer(client internalclientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.Prd().BackingServices().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.Prd().BackingServices().Watch(options)
			},
		},
		&prd.BackingService{},
		resyncPeriod,
		indexers,
	)
}

func defaultBackingServiceInformer(client internalclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewBackingServiceInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *backingServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&prd.BackingService{}, defaultBackingServiceInformer)
}

func (f *backingServiceInformer) Lister() internalversion.BackingServiceLister {
	return internalversion.NewBackingServiceLister(f.Informer().GetIndexer())
}
