/*
@asiainfo.com
*/

// This file was automatically generated by informer-gen

package internalversion

import (
	internalinterfaces "github.com/asiainfoldp/apiserver-servicebroker/pkg/client/informers_generated/internalversion/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// BackingServices returns a BackingServiceInformer.
	BackingServices() BackingServiceInformer
	// BackingServiceInstances returns a BackingServiceInstanceInformer.
	BackingServiceInstances() BackingServiceInstanceInformer
	// ServiceBrokers returns a ServiceBrokerInformer.
	ServiceBrokers() ServiceBrokerInformer
}

type version struct {
	internalinterfaces.SharedInformerFactory
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory) Interface {
	return &version{f}
}

// BackingServices returns a BackingServiceInformer.
func (v *version) BackingServices() BackingServiceInformer {
	return &backingServiceInformer{factory: v.SharedInformerFactory}
}

// BackingServiceInstances returns a BackingServiceInstanceInformer.
func (v *version) BackingServiceInstances() BackingServiceInstanceInformer {
	return &backingServiceInstanceInformer{factory: v.SharedInformerFactory}
}

// ServiceBrokers returns a ServiceBrokerInformer.
func (v *version) ServiceBrokers() ServiceBrokerInformer {
	return &serviceBrokerInformer{factory: v.SharedInformerFactory}
}
