/*
@asiainfo.com
*/

// This file was automatically generated by lister-gen

package v1

import (
	v1 "github.com/asiainfoldp/apiserver-servicebroker/pkg/apis/prd/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// BackingServiceInstanceLister helps list BackingServiceInstances.
type BackingServiceInstanceLister interface {
	// List lists all BackingServiceInstances in the indexer.
	List(selector labels.Selector) (ret []*v1.BackingServiceInstance, err error)
	// BackingServiceInstances returns an object that can list and get BackingServiceInstances.
	BackingServiceInstances(namespace string) BackingServiceInstanceNamespaceLister
	BackingServiceInstanceListerExpansion
}

// backingServiceInstanceLister implements the BackingServiceInstanceLister interface.
type backingServiceInstanceLister struct {
	indexer cache.Indexer
}

// NewBackingServiceInstanceLister returns a new BackingServiceInstanceLister.
func NewBackingServiceInstanceLister(indexer cache.Indexer) BackingServiceInstanceLister {
	return &backingServiceInstanceLister{indexer: indexer}
}

// List lists all BackingServiceInstances in the indexer.
func (s *backingServiceInstanceLister) List(selector labels.Selector) (ret []*v1.BackingServiceInstance, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.BackingServiceInstance))
	})
	return ret, err
}

// BackingServiceInstances returns an object that can list and get BackingServiceInstances.
func (s *backingServiceInstanceLister) BackingServiceInstances(namespace string) BackingServiceInstanceNamespaceLister {
	return backingServiceInstanceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// BackingServiceInstanceNamespaceLister helps list and get BackingServiceInstances.
type BackingServiceInstanceNamespaceLister interface {
	// List lists all BackingServiceInstances in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.BackingServiceInstance, err error)
	// Get retrieves the BackingServiceInstance from the indexer for a given namespace and name.
	Get(name string) (*v1.BackingServiceInstance, error)
	BackingServiceInstanceNamespaceListerExpansion
}

// backingServiceInstanceNamespaceLister implements the BackingServiceInstanceNamespaceLister
// interface.
type backingServiceInstanceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all BackingServiceInstances in the indexer for a given namespace.
func (s backingServiceInstanceNamespaceLister) List(selector labels.Selector) (ret []*v1.BackingServiceInstance, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.BackingServiceInstance))
	})
	return ret, err
}

// Get retrieves the BackingServiceInstance from the indexer for a given namespace and name.
func (s backingServiceInstanceNamespaceLister) Get(name string) (*v1.BackingServiceInstance, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("backingserviceinstance"), name)
	}
	return obj.(*v1.BackingServiceInstance), nil
}
