/*
@asiainfo.com
*/

// This file was automatically generated by lister-gen

package v1

// BackingServiceListerExpansion allows custom methods to be added to
// BackingServiceLister.
type BackingServiceListerExpansion interface{}

// BackingServiceInstanceListerExpansion allows custom methods to be added to
// BackingServiceInstanceLister.
type BackingServiceInstanceListerExpansion interface{}

// BackingServiceInstanceNamespaceListerExpansion allows custom methods to be added to
// BackingServiceInstanceNamespaceLister.
type BackingServiceInstanceNamespaceListerExpansion interface{}

// BindingListerExpansion allows custom methods to be added to
// BindingLister.
type BindingListerExpansion interface{}

// BindingNamespaceListerExpansion allows custom methods to be added to
// BindingNamespaceLister.
type BindingNamespaceListerExpansion interface{}

// ServiceBrokerListerExpansion allows custom methods to be added to
// ServiceBrokerLister.
type ServiceBrokerListerExpansion interface{}
