/*
@asiainfo.com
*/

// This file was automatically generated by lister-gen

package v1

import (
	v1 "github.com/asiainfoldp/apiserver-servicebroker/pkg/apis/prd/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ServiceBrokerLister helps list ServiceBrokers.
type ServiceBrokerLister interface {
	// List lists all ServiceBrokers in the indexer.
	List(selector labels.Selector) (ret []*v1.ServiceBroker, err error)
	// Get retrieves the ServiceBroker from the index for a given name.
	Get(name string) (*v1.ServiceBroker, error)
	ServiceBrokerListerExpansion
}

// serviceBrokerLister implements the ServiceBrokerLister interface.
type serviceBrokerLister struct {
	indexer cache.Indexer
}

// NewServiceBrokerLister returns a new ServiceBrokerLister.
func NewServiceBrokerLister(indexer cache.Indexer) ServiceBrokerLister {
	return &serviceBrokerLister{indexer: indexer}
}

// List lists all ServiceBrokers in the indexer.
func (s *serviceBrokerLister) List(selector labels.Selector) (ret []*v1.ServiceBroker, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ServiceBroker))
	})
	return ret, err
}

// Get retrieves the ServiceBroker from the index for a given name.
func (s *serviceBrokerLister) Get(name string) (*v1.ServiceBroker, error) {
	key := &v1.ServiceBroker{ObjectMeta: meta_v1.ObjectMeta{Name: name}}
	obj, exists, err := s.indexer.Get(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("servicebroker"), name)
	}
	return obj.(*v1.ServiceBroker), nil
}
